services:
  x-connector:
    container_name: x-connector
    restart: always
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    image: x-connector:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Europe/Kiev
    env_file:
      - .env
    networks:
      - think-root-network

networks:
  think-root-network:
    external: true 